version: 1.1.{build}
image: Visual Studio 2019
before_build:
 - dotnet restore
build_script:
 - dotnet build /verbosity:quiet "Fanray.sln"
test_script:
 - dotnet test --no-build .\test\Fan.Tests\Fan.Tests.csproj
 - dotnet test --no-build .\test\Fan.Blog.Tests\Fan.Blog.Tests.csproj
 - dotnet test --no-build .\test\Fan.Web.Tests\Fan.Web.Tests.csproj
 - dotnet test --no-build .\test\Shortcodes.Tests\Shortcodes.Tests.csproj
